# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iris.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'iris.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\niris.proto\"O\n\x11PredictionRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\t\x12\x12\n\nprediction\x18\x03 \x01(\t\"%\n\x12PredictionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x0bIrisService\x12\x39\n\x0eSavePrediction\x12\x12.PredictionRequest\x1a\x13.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iris_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=14
  _globals['_PREDICTIONREQUEST']._serialized_end=93
  _globals['_PREDICTIONRESPONSE']._serialized_start=95
  _globals['_PREDICTIONRESPONSE']._serialized_end=132
  _globals['_IRISSERVICE']._serialized_start=134
  _globals['_IRISSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
