# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x64\x65motut\"^\n\x06\x46lower\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x02 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\"\x1a\n\nPrediction\x12\x0c\n\x04pred\x18\x01 \x01(\x02\x32L\n\x11PredictionService\x12\x37\n\rGetPrediction\x12\x0f.demotut.Flower\x1a\x13.demotut.Prediction\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOWER']._serialized_start=26
  _globals['_FLOWER']._serialized_end=120
  _globals['_PREDICTION']._serialized_start=122
  _globals['_PREDICTION']._serialized_end=148
  _globals['_PREDICTIONSERVICE']._serialized_start=150
  _globals['_PREDICTIONSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
